# Hands on 1 - Troubleshooting tip: change this if 8090 is already in use
server.port=8090

# Hands on 3 - Incorporate Logging
logging.level.org.springframework=info
logging.level.com.cognizant.springlearn=debug
logging.pattern.console=%d{yyMMdd}|%d{HH:mm:ss.SSS}|%-20.20thread|%5p|%-25.25logger{25}|%25M|%m%n
